# Generated by Django 5.1.3 on 2024-11-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('change_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('page_url', models.URLField()),
                ('image', models.BinaryField(blank=True, null=True)),
                ('type_url', models.CharField(choices=[('website', 'Website'), ('book', 'Book'), ('article', 'Article'), ('music', 'Music'), ('video', 'Video')], default='website', max_length=100)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('change_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
