# Generated by Django 5.1.3 on 2024-11-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='heading',
            new_name='title',
        ),
        migrations.AddField(
            model_name='collection',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='links', to='links.link'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='user_collection_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='user_link_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
