# Generated by Django 5.1.3 on 2024-11-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_collection_description_alter_link_description_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='type_url',
            field=models.CharField(choices=[('website', 'Website'), ('book', 'Book'), ('article', 'Article'), ('music', 'Music'), ('video', 'Video')], default='website', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_collection_title'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('user', 'user_collection_id'), name='unique_user_collection'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('user', 'page_url'), name='unique_user_page_url'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('user', 'user_link_id'), name='unique_user_link'),
        ),
    ]
