services: 
  app:
    build: .
    container_name: TestedProject1
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: "cache"
      REDIS_PORT: "6379"
      SECRET_KEY: ${SECRET_KEY}  
    volumes: 
      - TestedProject1:/app
    
  db:
    image: postgres:14
    container_name: postgres_Db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data  
  
  cache:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
     - "6379:6379"
    volumes:
     - redis_data:/data

volumes:
  pgdata:
  redis_data: