services: 
  app:
    build: .
    container_name: TestedProject1
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cashe
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: cashe
      REDIS_PORT: 6379
      SECRET_KEY: ${SECRET_KEY}  
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT} 
      EMAIL_USE_SSL: ${EMAIL_USE_SSL} 
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}  
    volumes: 
      - ./TestedProject1:/app
    
  db:
    image: postgres:14
    container_name: postgres_for_TestedProject1_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data  
  
  cashe:
    image: redis:latest
    container_name: redis_for_TestedProject1_container
    restart: always
    ports:
     - "6379:6379"
    volumes:
     - redis_data:/data

volumes:
  pgdata:
  redis_data: