# Generated by Django 5.1.3 on 2024-11-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email_alter_user_hashed_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hashed_password',
            new_name='password',
        ),
    ]
